name: gold-price-prediction
region: nyc

services:
- name: web
  github:
    repo: YOUR_GITHUB_USERNAME/ML_gold_preditct_project
    branch: main
    deploy_on_push: true
  
  # Path to your webapp directory
  source_dir: /webapp
  
  # Build command
  build_command: pip install -r ../requirements.txt
  
  # Run command - uses Gunicorn for production
  run_command: gunicorn --bind 0.0.0.0:$PORT app:app --workers 2 --timeout 120
  
  # Environment variables
  envs:
  - key: PORT
    scope: RUN_TIME
    value: "8080"
  - key: PYTHON_VERSION
    scope: BUILD_TIME
    value: "3.9"
  
  # Resource configuration
  instance_count: 1
  instance_size_slug: basic-xxs  # $5/month - 512MB RAM, 1 vCPU
  
  # Routing
  routes:
  - path: /
  
  # Health check
  health_check:
    http_path: /health
    initial_delay_seconds: 20
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  
  # Alerts
  alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
